- name: running command 'mkdir -p /var/pv/{1,2,3,4}'
  command: mkdir -p /var/pv/{1,2,3,4}
  ignore_errors: no

- name: running command 'chmod 777 /var/pv/{1,2,3,4}'
  command: chmod 777 /var/pv/{1,2,3,4}
  ignore_errors: no

- name: Open port 24007 (GlusterFS daemon)
  firewalld: port=24007/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open port 24008 (GlusterFS management)
  firewalld: port=24008/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open port 2222 (GlusterFS sshd)
  firewalld: port=2222/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Open ports 49152-49251 (GlusterFS bricks)
  firewalld: port=49152-49251/tcp zone=trusted permanent=true state=enabled immediate=true

- name: Pull GlusterFS Docker image
  command: docker pull gluster/gluster-centos:latest
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 1

- name: Pull heketi Docker image
  command: docker pull heketi/heketi:dev
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 1
